FROM ubuntu:16.04
WORKDIR /frontend-example-docker
RUN apt-get update && apt-get install -y curl git nodejs \
&& curl -sL https://deb.nodesource.com/setup_10.x | bash \
&& git clone https://github.com/docker-hy/frontend-example-docker . \
&& apt-get purge -y --auto-remove curl \
&& apt-get purge -y --auto-remove git \
&& rm -rf /var/lib/apt/lists/* \
RUN npm install \
&& rm -rf /app/.git
EXPOSE 5000
ENV API_URL=http://localhost:8000
CMD npm start
