version: '3.5'
services:
  m-frontend:
    build: https://github.com/docker-hy/ml-kurkkumopo-frontend.git
    ports:
      - 3000:3000
  m-backend:
    build: https://github.com/docker-hy/ml-kurkkumopo-backend.git
    ports:
      - 5000:5000
    volumes:
      - model:/src/model
  m-training:
    build: https://github.com/docker-hy/ml-kurkkumopo-training.git
    volumes:
      - model:/src/model
      - imgs:/src/imgs
      - data:/src/data
volumes:
  model:
  imgs:
  data:
